### ISSUE TITLE
Failing as a part of the release cycle

### ISSUE THREAD

**Issue by ygizhitsa** [Duber/vsts-smoke-web-test-task#1]
Probably because if the empty Name label and not ability to change it on  Save

2017-03-03T21:38:45.2597971Z ##[section]Error: System.ArgumentException: Context name can not be null or empty.
 
2017-03-03T21:38:45.2597971Z Parameter name: name
 
2017-03-03T21:38:45.2597971Z    at Microsoft.TeamFoundation.DistributedTask.Agent.Worker.Common.BaseContext..ctor(ILogContext parentContext, ILogger logger, Guid scopeId, Guid timelineId, String rootFolder, String workFolder, Boolean logToFile, String name, String type, String loggingArea)
 
2017-03-03T21:38:45.2597971Z    at Microsoft.TeamFoundation.DistributedTask.Agent.Worker.Common.TaskContext..ctor(IJobContext jobContext, ILogger logger, Guid taskInstanceId, String taskName, IJobExtension jobExtension)
 
2017-03-03T21:38:45.2597971Z    at Microsoft.TeamFoundation.DistributedTask.Agent.Worker.Common.JobContext.CreateTaskContext(Guid taskInstanceId, String taskName, Boolean logInitialization)
 
2017-03-03T21:38:45.2597971Z    at Microsoft.TeamFoundation.DistributedTask.Plugin.Release.ReleaseJobExtension.InitializeTaskContexts(IJobContext context, IJobRequest job)
 
2017-03-03T21:38:45.2597971Z    at Microsoft.TeamFoundation.DistributedTask.Plugin.Release.ReleaseJobExtension.InitializeAgent(IJobContext context, IJobRequest job, ITaskContext& downloadArtifactTaskContext, String& teamProjectId, Uri& artifactsWorkingFolder, Int32& releaseId)
 
2017-03-03T21:38:45.2910779Z ##[error]Context name can not be null or empty.
 
2017-03-03T21:38:45.2910779Z ##[error]Parameter name: name

**Comment by Duber** [comment]
@ygizhitsa thanks for reporting. I will look into this asap.

**Comment by ygizhitsa** [comment]
Wondering if you had a chance to look at the issue?

**Comment by Duber** [comment]
Hello,

I Couldn't reproduce your bug but I fixed the label thing. 
Now you can change the name/label of the task step. 
Can you try ?
